name: Hello GH Actions ğŸŒ

on:
    push:

jobs:
    Hello-world:
        runs-on: ubuntu-latest
        steps:
            -   name: My first step in GH Action
                run: echo "Hello actions!"
